### ISSUE TITLE
Type checking fails because of implicit any return type

### ISSUE THREAD

**Issue by traverse** [mailslurp/mailslurp-client#14]
Currently the type checking in our project fails because of the following line:
https://github.com/mailslurp/mailslurp-client-ts-js/blob/49ec35c5c8c8a71d51633f67b23d9d57e78f4c1c/index.ts#L46

I'm not sure what the correct response type should be, maybe `Promise<Response>`, but currently it doesn't have any which makes type checking fail in strict mode.

**Comment by jackmahoney** [comment]
Thanks for opening this issue! We have fixed this in version 4.3.2. Thanks again
