### ISSUE TITLE
How to enable debug mode in js api

### ISSUE THREAD

**Issue by orihomie** [mailslurp/mailslurp-client#19]
The question is: 
* is there any option to enable debug mode so I'll see all incoming and outgoing requests from api so wont need to dig into lib and put there endless count of console.log(something) ?
OR
* is there option to develop such option?

**Comment by jackmahoney** [comment]
yes there is, have a look at the source code. It uses npm debug under the hood. You can enable this following the npm debug module instructions.

**Comment by orihomie** [comment]
I'll point that debug mode pointed by author - not the best since it's just show you http responses, not requests, requests will be marked as "%somefunction% executing...", so, if anyone get here with same question - you should find out mailslurp-swagger lib in node_modules, find there /dist/api.js, put some logging in functions you need and then have a joy while having conversation with this author.

**Comment by orihomie** [comment]
And keep in mind - enabling logging via (it's in my codeceptjs's test 'Before' method)
> process.env.DEBUG='*'

somehow wont work for this library >:( (while working fine for other libs like mssql)
