### ISSUE TITLE
deleteWebhook documentation is incorrect

### ISSUE THREAD

**Issue by nmummau** [mailslurp/mailslurp-client#20]
**Steps to reproduce**
1. Navigate here to the [deleteWebhook](https://github.com/mailslurp/mailslurp-client/blob/master/docs/classes/mailslurp.md#deletewebhook) documentation.
2. The description incorrectly describes deletion.

**Comment by nmummau** [comment]
If you're open to a PR, I fixed this issue and also cleaned up a few other documentation discrepancies. Including adding details, where missing, to index.ts. I have a feature branch if you're open to it.

**Comment by jackmahoney** [comment]
Thanks for offering @nmummau . PRs are definitely welcome. I'm planning to redocument the client this weekend so let's see how that goes first and then you can open a PR afterwards if you like.

**Comment by nmummau** [comment]
Yeah I saw your [documentation](https://github.com/mailslurp/documentation). I have some suggestions in that project too, if you're open to it.
