### ISSUE TITLE
getWebhooks requires a UUID but that isn't described in documentation

### ISSUE THREAD

**Issue by nmummau** [mailslurp/mailslurp-client#22]
In some preliminary testing of MailSlurp, I setup code to call `getWebhooks('1')`. 
This rejected with an unfriendly message.

```
{
  message:  'Failed to convert value of type \'java.lang.String\' to required type \'java.util.UUID\'; nested exception is java.lang.IllegalArgumentException: Invalid UUID string: 1'
}
```

It would be nice if this was documented, that it needs to be a UUID, rather than just a simple string. Additionally, a nicer response message would be nice, instead of the caught exception.

**Comment by jackmahoney** [comment]
Thanks for pointing this out. We have released a new docs site at [docs.mailslurp.com](https://docs.mailslurp.com/js/classes/mailslurp/). The method signature says inboxId there: `▸ getWebhooks(inboxId: string): Promise<Webhook[]>`

**Comment by jackmahoney** [comment]
But thanks for the feedback I'll consider adding better exceptions
