### ISSUE TITLE
Required UUID parameter 'inboxId' is not present

### ISSUE THREAD

**Issue by georgeben** [mailslurp/mailslurp-client#29]
When I try to wait for a matching email, I get the error: `Required UUID parameter 'inboxId' is not present`
Here is my code
```js
const email = await mailSlurp.waitForMatchingEmails({
            inboxId,
            count: 1,
            matchOptions: [
                {
                    field: "SUBJECT",
                    should: "CONTAIN",
                    value: "Hellol"
                }
            ]
        });
```
Please what am I doing wrong?

**Comment by jackmahoney** [comment]
Is the value of inboxId null or undefined? You may be passing the value as empty.

Can you share more code?

Here is the documentation for the method, check your code with that too:

https://github.com/mailslurp/mailslurp-client/blob/master/docs/classes/_index_.mailslurp.md#waitformatchingemails
