### ISSUE TITLE
CypressError:Required UUID parameter 'inboxId' is not present 

### ISSUE THREAD

**Issue by AkramPasha** [mailslurp/mailslurp-client#32]
Hi ,

I am trying to fetch a mail based on the content of the subject
Following is the custom command created :

Cypress.Commands.add("fetchMail", inboxId => {
  return mailslurp.waitForMatchingEmails({
    inbox: inboxId,
    count: 1,
    timeout: 30000,
    matchOptions: [
      {
        field: "SUBJECT",
        should: "CONTAIN",
        value: "User verification code"
      }
    ]
  });

})

please let me know the usage/the correct format to fetch the mail based on the subject contains.

Getting : CypressError:Required UUID parameter 'inboxId' is not present

**Comment by jackmahoney** [comment]
Hi sorry im closing this as more context is needed.

**Comment by AkramPasha** [comment]
Hi @jackmahoney 

Thank you for your reply ,

Scenario :

As i have 5 mail in my mailslurp inbox , as i need to fetch the 3rd mail content [And also the mail being received is also not a fixed location ex : The mail can be in any position ] . So i tried with fetching the mail content based on the subject content.
Using the following lines of code 

Cypress.Commands.add("fetchMail", inboxId => {
return mailslurp.waitForMatchingEmails({
inbox: inboxId,
count: 1,
timeout: 30000,
matchOptions: [
{
field: "SUBJECT",
should: "CONTAIN",
value: "User verification code"
}
]
});

})

But when i try to run the scenario i am getting : **CypressError:Required UUID parameter 'inboxId' is not present** 
error message in the test runner .Even i have passed the inboxid also .

Thanks in Advance

**Comment by landlight** [comment]
> Hi @jackmahoney
> 
> Thank you for your reply ,
> 
> Scenario :
> 
> As i have 5 mail in my mailslurp inbox , as i need to fetch the 3rd mail content [And also the mail being received is also not a fixed location ex : The mail can be in any position ] . So i tried with fetching the mail content based on the subject content.
> Using the following lines of code
> 
> Cypress.Commands.add("fetchMail", inboxId => {
> return mailslurp.waitForMatchingEmails({
> inbox: inboxId,
> count: 1,
> timeout: 30000,
> matchOptions: [
> {
> field: "SUBJECT",
> should: "CONTAIN",
> value: "User verification code"
> }
> ]
> });
> 
> })
> 
> But when i try to run the scenario i am getting : **CypressError:Required UUID parameter 'inboxId' is not present**
> error message in the test runner .Even i have passed the inboxid also .
> 
> Thanks in Advance

You might be wrong since you are using inbox instead of inboxId. However, I am trying out to call this same API with inboxId parameter but it keeps replying me with CypressError:Required UUID parameter 'inboxId' is not present even though it is the correct UUID string. Hope you guys can take a look for this API @jackmahoney 
The other APIs like waitForLatestEmail and other ones work, the bug is only occurring in waitForMatchingEmails I guess.

## Edit
I found out that we have to call the parameters as defined in the method due to typescript checking 
(matchOptions, count, inboxId, ...etc) 
It would be great if you could give us an example of matchingOptions in the documentation or example since I cannot resolve that at all.

**Comment by jackmahoney** [comment]
Ah i see. Okay good idea. I will improve the matching docs

**Comment by vladMocan** [comment]
@jackmahoney any update on this issue? I can't find the documentation update.

**Comment by jackmahoney** [comment]
Hi @vladMocan I would recommend using the Cypress plugin directly if using with Cypress.

https://github.com/mailslurp/cypress-mailslurp.

For the above situation the user is passing an object not individual params.

Note: `waitForMatchingEmails({ ... })` it should be  

```typescript
    async waitForMatchingEmails(
        matchOptions: MatchOptions,
        count?: number,
        inboxId?: string,
        timeout?: number,
        unreadOnly?: boolean
    ): Promise<EmailPreview[]> 
```
