### ISSUE TITLE
Requesting emails returns "Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID"

### ISSUE THREAD

**Issue by lynscott** [mailslurp/mailslurp-client#34]
I've tried this library, your SDK integration with cypress-js, rolling my own integration in cypress-js with the mailslurp REST API, and just using a regular curl command from my terminal. 

All methods to request emails ( either all or wait for latest email ) have returned this java type error.  `{"message":"Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'; nested exception is java.lang.IllegalArgumentException: Invalid UUID string: 982400b8"}`

[Error Screenshot](https://user-images.githubusercontent.com/29384350/91212567-42177200-e6c5-11ea-9379-2e1c64266d32.png)

**Comment by gabrielgrover** [comment]
When using your npm package I get the same error when using the waitForLatestEmail method.

**Comment by landlight** [comment]
email.id doesn't really work. You have to concat the all the data from the start to the point of @mailslurp.com in order to use the methods.

**Comment by jackmahoney** [comment]
Thanks for reporting this, sorry for the delay. I had been trying to get to the bottom of this bug myself. Could you please post some code that replicates the exception?

**Comment by jackmahoney** [comment]
Ah. This isn't technically a bug as you are passing a shortId instead of the id. We (bad design) display the shortId in the dashboard in many places. But you must use the full ID displayed in the URLs. I will try to add a better message as the exception however so will leave this open until updated.

**Comment by lynscott** [comment]
Little confused on this, so the id of the inbox is found in the url of the inbox?
