### ISSUE TITLE
Provide documentation for MatchOptions when calling waitForMatchingEmails

### ISSUE THREAD

**Issue by landlight** [mailslurp/mailslurp-client#35]
I got the following error when try to call the **waitForMatchingEmails**
```
JSON parse error: Cannot deserialize instance of 
com.mailslurp.lib.dtos.MatchOptions out of START_ARRAY token; 
nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: 
Cannot deserialize instance of com.mailslurp.lib.dtos.MatchOptions 
out of START_ARRAY token
 at [Source: (PushbackInputStream); line: 1, column: 1]
```

```
Cypress.Commands.add('getMatchingEmail', async(inboxId, count, matchText) => {
  const matchOptions = [
    {
      "field": "SUBJECT",
      "should": "CONTAIN",
      "value": matchText 
    }
  ]
  return await mailslurp.waitForMatchingEmails(matchOptions, count, inboxId)
})
```

I tried out with the method example from official documentation of mailslurp but it doesn't work due to the typescript checking from mailslurp client.
[mailslurp documentation](https://www.mailslurp.com/guides/receiving-emails/#matching-and-searching-emails)
```
const welcomeEmail = await mailslurp.waitForMatchingEmails({
  inboxId,
  count,
  matchOptions: [
    {
      field: "SUBJECT",
      should: "CONTAIN",
      value: "Welcome!"
    }
  ]
});
```
I am pretty sure #29 and #32 are having the same problem due to this. 

It would be awesome if you could provide us the info on how we can call this function.

**Comment by jackmahoney** [comment]
Thanks for raising this issue. I'll think of a way to improve this and post the update here.

**Comment by landlight** [comment]
I solved it after updating my cypress into typescript but it would be great to have a solvable solution for JS.

**Comment by jackmahoney** [comment]
Thanks! I agree. We will try to improve our documentation this month.
