### ISSUE TITLE
waitForMatchingEmail results don't include body

### ISSUE THREAD

**Issue by alvaromartmart** [mailslurp/mailslurp-client#36]
I'm using `mailSlurp.waitController.waitForMatchingEmail` to retrieve some emails based on the subject.
The returned emails, however, don't include the email body (while waitForLatestEmail did).

It is unclear to me if I have to fetch the contents of those emails explicitly, am I missing something?

``` ts
mailSlurp.waitController
    .waitForMatchingEmail(
      {
        matches: [
          {
            should: MatchOption.ShouldEnum.CONTAIN,
            value: subject,
            field: MatchOption.FieldEnum.SUBJECT
          }
        ]
      },
      count,
      inboxId
    )
    .then(emails => {
      return Promise.all(emails.map(e => mailSlurp.emailController.getEmail(e.id)));
    });
```

**Comment by jackmahoney** [comment]
Hi, thanks for raising this, I will write a test for this soon and reply with an update. Cheers!

**Comment by jackmahoney** [comment]
Yes you are correct, one must fetch each email body seperately, but you should be careful when calling in parallel to avoid rate limits and large file sizes because the full email is fetched.
