### ISSUE TITLE
Add example of how to use the raw API

### ISSUE THREAD

**Issue by jinjor** [mailslurp/mailslurp-client#4]
Hi, I recently started to use MailSlurp and found it very useful for doing end-to-end test. Thank you for making this great service and libraries!

I thing the document would be more user-friendly if there is an example to use the raw swagger-generated API. I'm not a TypeScript expert so that it took me several time to find the following code is possible.

```typescript
import { Inbox, EmailControllerApi, Email } from "mailslurp-swagger-sdk-ts";

...

async function deleteEmail(email: Email): Promise<void> {
    const rawEmailApi = new EmailControllerApi({ apiKey });
    await rawEmailApi.deleteEmailUsingDELETE(email.id);
}
```

How do you think?

**Comment by jackmahoney** [comment]
Thanks @jinjor I appreciate your feedback. Yes that does sound like a useful idea. The documentation in general could definitely be improved. I will use this to improve the current libraries. Thanks, Jack
