### ISSUE TITLE
waitForMatchingFirstEmail not working

### ISSUE THREAD

**Issue by santii90** [mailslurp/mailslurp-client#44]
The method is on documentation but looks like is not fully implemented. I'm getting this error when trying to use it on Cypress with JS. 
`TypeError: mailslurp.waitForMatchingFirstEmail is not a function`

**Comment by jackmahoney** [comment]
Hi I believe this function is available on the `waitController` property.

So `mailslurp.waitController.waitForMatchingFirstEmail()`
