### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by buesing** [mailslurp/mailslurp-client#47]
Hi, is it possible to see the changelogs anywhere? I was going to update from v12 to 13, but Github releases don't seem to be used since version 3 and on npm I also couldn't find anything. How can I know what the breaking changes were?

**Comment by jackmahoney** [comment]
Sorry we don't publish the central change log but I will add this to a TODO thanks. We usually include the changes in the commit message with the release tag.

**Comment by buesing** [comment]
@jackmahoney So there were no breaking changes in this upgrade? Could you only increment the minor version number or patch in this case? When upgrading libraries, a major version increment implies a breaking API change, and this is impossible to figure out without changelogs.
