### ISSUE TITLE
retryTimeout used with getEmails function throws 400

### ISSUE THREAD

**Issue by drptbl** [mailslurp/mailslurp-client#5]
@klamping @jackmahoney

Code example:
```js
const { MailSlurp } = require('mailslurp-client');
const api = new MailSlurp({
  apiKey: 'test'
});
async function test() {
  try {
    const inbox = await api.createInbox();
    const emails = await api.getEmails(inbox.id, { minCount: 1, retryTimeout: 120000 });
    console.log('emails', emails[0].id);
  } catch (err) {
    console.error(err);
  }
}
test();
```

While passing `retryTimeout` inside `getEmails`, it throws:
```
url:
   'https://api.mailslurp.com/inboxes/<EDITED>/emails?minCount=1&retryTimeout=120000',
  status: 400,
  statusText: 'Bad Request'
```

**Comment by jackmahoney** [comment]
Thank you for reporting this. It could be that the documentation for
required parameters has diverged. Smoke tests for this functionality are
passing. I will examine your code example and post a solution soon. Please
also check your usage against the documentation at docs.MailSlurp.com

**Comment by jackmahoney** [comment]
Could be that the retry timeout exceeds the maximum. Was a message returned
with your 400?

**Comment by drptbl** [comment]
@jackmahoney Thanks. There was no message returned. Error was raised instantly after running code example, so retry timeout couldn't exceed maximum (120 seconds in example). If there is API limitation on maximum amount to wait with `retryTimeout`, I'm not sure what value it is and there is no mention about it in docs.

After checking documentation:
https://docs.mailslurp.com/#operation--inboxes--id--emails-get

There is written:
> The server will retry the inbox database until the minCount is satisfied **or** the retryTimeout is reached.

I've just re-tested this and after removing `minCount` and leaving `retryTimeout` alone - it seems to work (doesn't throw error instantly):
```js
    const emails = await api.getEmails(inbox.id, { retryTimeout: 120000 })
``` 
However I would like to combine these two (`minCount` with `retryTimeout`). Documentation also suggests that they can be used together:

> minCount: integer (int64)
> in query
> Minimum acceptable email count. Will cause request to hang **(and retry)** until minCount is satisfied **or retryTimeout** is reached.
> 
> retryTimeout: integer (int64)
> in query
> Maximum milliseconds to spend retrying inbox database **until minCount** emails are returned

Thanks for investigating 👍.

**Comment by jackmahoney** [comment]
@drptbl so I looked at the client usage in our end-to-end tests and I can see that it is passing using `minCount` and `retryTimeout` together. The code is posted below. I checked the source for the API and the max-retry-timeout is 60000 milliseconds so I believe your 400 is due to your 120000 exceeding this value. I have increased the timeout to 180000 now and it is deploying as we speak. Please try again in 30 minutes.

For reference, our tests:
```javascript
const {MailSlurp} = require("mailslurp-client");
const api = new MailSlurp({apiKey: "test"});
jest.setTimeout(60000);

describe("javascript client", async () => {
    it("can get inboxes for test user", async () => {
        const inboxes = await api.getInboxes();
        expect(inboxes).not.toBeNull();
    });
    it("can create an inbox, fetch it, and delete it", async () => {
        const inbox = await api.createInbox();
        expect(inbox).not.toBeNull();
        expect(inbox.id).not.toBeNull();
        const fetchedInbox = await api.getInbox(inbox.id);
        expect(inbox).toMatchObject(fetchedInbox);
        const response = await api.deleteInbox(inbox.id);
        expect(response).not.toBeNull();
    });
    it("can send emails and then get them", async () => {
        const body = "test-email-body-" + Date.now();
        const subject = "test-email-subject-" + Date.now();
        const inbox = await api.createInbox();
        await api.sendEmail(inbox.id, {
            body,
            subject,
            to: [inbox.emailAddress],
        });
        // >>>>>>>>>> Here is where we get emails
        const messages = await api.getEmails(inbox.id, {
            limit: 1,
            minCount: 1,
            retryTimeout: 60000,
            since: new Date()
        });
        expect(messages.length).toEqual(1);
        const email = await api.getEmail(messages[0].id);
        expect(email.subject).toBe(subject);
        expect(email.body).toContain(body);
        expect(email.headers).toBeTruthy();
        // can get raw etc
        expect(email.rawUrl).toContain("https://s3-us-west-2.amazonaws.com/mailslurp-emails/");
        console.log(email.rawUrl);
        const response = await fetch(email.rawUrl);
        // expect(response.status).toEqual(200);
        // expect(response.text()).toEqual("Test");
        
        // now delete
        const deleteRes = await api.deleteInbox(inbox.id)
        expect(deleteRes.status).toEqual(204)
    })
});
```

**Comment by jackmahoney** [comment]
@drptbl I can confirm the API now supports retryTimeout of 120000 (up to 180000 max) and minCount in same request.
```javascript
        const messages = await api.getEmails(inbox.id, {
            limit: 1,
            minCount: 1,
            retryTimeout: 120000,
            since: new Date()
        });
```

**Comment by drptbl** [comment]
@jackmahoney Thanks for investigation 👍. I can confirm it works now. Cheers!
